/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import conexion.Conexion;
import controlador.ControladorPelicula;
import controlador.ControladorSala;
import controlador.ControlarFuncion;
import controlador.ControladorVista;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;
import model.FuncionE;
import model.Pelicula;
import model.Sala;

/**
 *
 * @author krizz
 */
public class Agregar_funcion extends javax.swing.JFrame {

    /**
     * Creates new form Agregar_funcion
     */
    private ControlarFuncion cFuncion;
    private Conexion conexion;
    ControladorVista cv = new ControladorVista();

    public Agregar_funcion() {
        initComponents();
        setTitle("Cine.in");
        this.setLocationRelativeTo(null);
        Cargarsala();
        this.setcFuncion(new ControlarFuncion());
        this.llenarTablaFun();
        Cargarpelicula();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public Conexion getConexion() {
        return conexion;
    }

    public void setConexion(Conexion conexion) {
        this.conexion = conexion;
    }

    public ControlarFuncion getcFuncion() {
        return this.cFuncion;
    }

    public void setcFuncion(ControlarFuncion ncFuncion) {
        this.cFuncion = ncFuncion;
    }

    private void Cargarsala() {
        ControladorSala csa = new ControladorSala();
        List<Sala> lista = csa.listarSala();
        for (int i = 0; i < lista.size(); i = i + 1) {
            Sala sal = new Sala(lista.get(i).getId_sala());
            salacombox.addItem(String.valueOf(sal.getId_sala()));
            CBsala.addItem(String.valueOf(sal.getId_sala()));
        }
    }

    private void Cargarpelicula() {
        ControladorPelicula ple = new ControladorPelicula();
        List<Pelicula> lista = ple.listarPeliculas();
        for (int i = 0; i < lista.size(); i = i + 1) {
            Pelicula pel = new Pelicula(lista.get(i).getId_pelicula(), lista.get(i).getNombre());
            pelibox.addItem(String.valueOf(pel.getId_pelicula()));
            pelibox1.addItem(String.valueOf(pel.getId_pelicula()));
        }
    }

    private void llenarTablaFun() {
        //jTable1
        String[] columnas = {"id_funcion", "Fecha", "Horainicio", "Horafinal", "Acti_funcion", "id_sala", "Id_pelicula"};
        DefaultTableModel dModel = new DefaultTableModel(columnas, 0);
        List<FuncionE> funciones = this.getcFuncion().listarFunciones();
        for (FuncionE funcione : funciones) {
            dModel.addRow(funcione.datosTabla());
        }
        jTable1.setModel(dModel);
    }

    private boolean verificaVacios1() {
        boolean valido = false;
        if (DCfecha1.getDate() != null && !TXThi1.getText().equals("") && !TXThf1.getText().equals("")) {
            valido = true;
        }
        return valido;
    }

    private boolean verificaSeleccion1() {
        boolean valido = true;
        if (CBsala.getSelectedIndex() == 0 || pelibox1.getSelectedIndex() == 0) {
            valido = false;
        }
        return valido;
    }

    private boolean verificaVacios2() {
        boolean valido = false;
        if (DCfecha2.getDate() != null && !TXThi2.getText().equals("") && !TXThf2.getText().equals("") && TXTid.getText().equals("")) {
            valido = true;
        }
        return valido;
    }

    private boolean verificaSeleccion2() {
        boolean valido = true;
        if (salacombox.getSelectedIndex() == 0 || pelibox.getSelectedIndex() == 0) {
            valido = false;
        }
        return valido;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DCfecha1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        TXThf1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TXThi1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ButtonAgregar = new javax.swing.JButton();
        ButtonVolver = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Comboacti_fun = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        peli = new javax.swing.JLabel();
        pelibox = new javax.swing.JComboBox<>();
        salacombox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        TXTid = new javax.swing.JTextField();
        ButtonBuscar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        DCfecha2 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        TXThi2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TXThf2 = new javax.swing.JTextField();
        CBsala = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        ButtonEli = new javax.swing.JButton();
        ButtonMod = new javax.swing.JToggleButton();
        ButtonVolver2 = new javax.swing.JToggleButton();
        jLabel13 = new javax.swing.JLabel();
        activo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        pelibox1 = new javax.swing.JComboBox<>();
        peli1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Agregar funcion");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Hora de Inicio HH:MM");

        DCfecha1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DCfecha1KeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Seleccione la fecha");

        TXThf1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXThf1KeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Hora de Fin HH:MM");

        TXThi1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXThi1KeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Seleccione la sala");

        ButtonAgregar.setText("Agregar");
        ButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarActionPerformed(evt);
            }
        });

        ButtonVolver.setText("Volver");
        ButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVolverActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cine.jpg"))); // NOI18N

        Comboacti_fun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Activada");

        peli.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        peli.setText("Id_pelicula");

        pelibox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione id Pelicula" }));
        pelibox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peliboxActionPerformed(evt);
            }
        });

        salacombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la sala" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXThi1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(DCfecha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(TXThf1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(salacombox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(89, 89, 89)
                                        .addComponent(Comboacti_fun, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(549, 549, 549)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(peli)
                                            .addComponent(pelibox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(ButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 15, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(peli))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Comboacti_fun, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(pelibox)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DCfecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXThi1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXThf1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salacombox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(ButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        jTabbedPane1.addTab("Agregar", jPanel1);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setText("Lista de funciones");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Volver ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addGap(97, 97, 97)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111))
        );

        jTabbedPane1.addTab("Lista", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Ingrese la ID");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 30, -1, -1));

        TXTid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTidKeyTyped(evt);
            }
        });
        jPanel3.add(TXTid, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 34, 200, -1));

        ButtonBuscar.setText("Buscar");
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(ButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 33, 113, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Fecha");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 73, -1, -1));
        jPanel3.add(DCfecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 108, 208, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Hora inicio HH:MM");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 149, -1, -1));

        TXThi2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXThi2KeyTyped(evt);
            }
        });
        jPanel3.add(TXThi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 184, 208, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Hora de Fin HH:MM");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 225, -1, -1));

        TXThf2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXThf2KeyTyped(evt);
            }
        });
        jPanel3.add(TXThf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 208, 30));

        CBsala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione sala" }));
        jPanel3.add(CBsala, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 336, 208, 29));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Sala");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 301, -1, -1));

        ButtonEli.setText("Eliminar");
        ButtonEli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliActionPerformed(evt);
            }
        });
        jPanel3.add(ButtonEli, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 473, 138, 40));

        ButtonMod.setText("Modificar");
        ButtonMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonModActionPerformed(evt);
            }
        });
        jPanel3.add(ButtonMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 473, 138, 40));

        ButtonVolver2.setText("Volver");
        ButtonVolver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVolver2ActionPerformed(evt);
            }
        });
        jPanel3.add(ButtonVolver2, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 473, 129, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Activacion");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 371, -1, -1));

        activo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));
        jPanel3.add(activo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 406, 203, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cine.jpg"))); // NOI18N
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 108, 352, -1));

        pelibox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione id Pelicula" }));
        pelibox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelibox1ActionPerformed(evt);
            }
        });
        jPanel3.add(pelibox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 402, 185, 34));

        peli1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        peli1.setText("Id_pelicula");
        jPanel3.add(peli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 407, -1, -1));
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, 50, 30));
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 50, 30));

        jTabbedPane1.addTab("Buscar", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 28, 790, 610));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar Fun.jpg"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVolverActionPerformed
        dispose();
        Menu_admin menu = new Menu_admin();
        menu.show();
    }//GEN-LAST:event_ButtonVolverActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        Menu_admin men = new Menu_admin();
        men.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarActionPerformed
        
            if (verificaVacios1()) {
                Date fecha = DCfecha1.getDate();
                long d = fecha.getTime();
                java.sql.Date fecha2 = new java.sql.Date(d);
                String horainicio = TXThi1.getText();
                String horafinal = TXThf1.getText();
                int activacion = Comboacti_fun.getSelectedIndex();
                int sala = salacombox.getSelectedIndex();
                int pelicula = pelibox.getSelectedIndex();
                FuncionE funciones = new FuncionE(fecha2, horainicio, horafinal, activacion, sala, pelicula);
                if (this.getcFuncion().agregarFuncion(funciones)) {

                    JOptionPane.showMessageDialog(null, "Funcion agregada");

                } else {
                    JOptionPane.showMessageDialog(null, "Funcion no agregada");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Por favor rellene la información");
            }
        
    }//GEN-LAST:event_ButtonAgregarActionPerformed

    private void ButtonVolver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVolver2ActionPerformed
        dispose();
        Menu_admin men = new Menu_admin();
        men.show();

    }//GEN-LAST:event_ButtonVolver2ActionPerformed

    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed
        FuncionE fun = this.getcFuncion().buscarFuncion(Integer.parseInt(TXTid.getText()));
        if (fun == null) {
            JOptionPane.showMessageDialog(null, "Funcion no existe");
        } else {
            System.out.println("Funcion encontrada");
            DCfecha2.setDate(fun.getFecha());
            TXThi2.setText(fun.getHorainicio());
            TXThf2.setText(fun.getHorafinal());
            CBsala.setSelectedIndex(fun.getSala());
            pelibox1.setSelectedIndex(fun.getId_pelicula());
            activo.setSelectedIndex(fun.getActi_fun());
        }
    }//GEN-LAST:event_ButtonBuscarActionPerformed

    private void ButtonEliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliActionPerformed
        if (!TXTid.getText().equals("")) {
            if (this.getcFuncion().eliminarFuncion(Integer.parseInt(TXTid.getText()))) {
                JOptionPane.showMessageDialog(null, "Funcion eliminada");
            } else {
                JOptionPane.showMessageDialog(null, "No se elimino");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese una id para eliminar la función");
        }
    }//GEN-LAST:event_ButtonEliActionPerformed

    private void peliboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peliboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peliboxActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        llenarTablaFun();
    }//GEN-LAST:event_actualizarActionPerformed

    private void pelibox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelibox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pelibox1ActionPerformed

    private void DCfecha1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DCfecha1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_DCfecha1KeyTyped

    private void TXThi1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXThi1KeyTyped
        char tecla = evt.getKeyChar();
        boolean es = false;
        if (cv.validarHora(tecla)) {
            es = true;
        }
        if (!es) {
            evt.consume();
        }
    }//GEN-LAST:event_TXThi1KeyTyped

    private void ButtonModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonModActionPerformed

    }//GEN-LAST:event_ButtonModActionPerformed

    private void TXThf1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXThf1KeyTyped
        char tecla = evt.getKeyChar();
        boolean es = false;
        if (cv.validarHora(tecla)) {
            es = true;
        }
        if (!es) {
            evt.consume();
        }
    }//GEN-LAST:event_TXThf1KeyTyped

    private void TXThi2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXThi2KeyTyped
        char tecla = evt.getKeyChar();
        boolean es = false;
        if (cv.validarHora(tecla)) {
            es = true;
        }
        if (!es) {
            evt.consume();
        }
    }//GEN-LAST:event_TXThi2KeyTyped

    private void TXThf2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXThf2KeyTyped
        char tecla = evt.getKeyChar();
        boolean es = false;
        if (cv.validarHora(tecla)) {
            es = true;
        }
        if (!es) {
            evt.consume();
        }
    }//GEN-LAST:event_TXThf2KeyTyped

    private void TXTidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTidKeyTyped
        char tecla = evt.getKeyChar();
        boolean es = false;
            if (cv.validarNumero(tecla)) {
                es = true;
            }
        if (!es) {
            evt.consume();
        }
    }//GEN-LAST:event_TXTidKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_funcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_funcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_funcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_funcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_funcion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAgregar;
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonEli;
    private javax.swing.JToggleButton ButtonMod;
    private javax.swing.JButton ButtonVolver;
    private javax.swing.JToggleButton ButtonVolver2;
    private javax.swing.JComboBox<String> CBsala;
    private javax.swing.JComboBox<String> Comboacti_fun;
    private com.toedter.calendar.JDateChooser DCfecha1;
    private com.toedter.calendar.JDateChooser DCfecha2;
    private javax.swing.JTextField TXThf1;
    private javax.swing.JTextField TXThf2;
    private javax.swing.JTextField TXThi1;
    private javax.swing.JTextField TXThi2;
    private javax.swing.JTextField TXTid;
    private javax.swing.JComboBox<String> activo;
    private javax.swing.JButton actualizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel peli;
    private javax.swing.JLabel peli1;
    private javax.swing.JComboBox<String> pelibox;
    private javax.swing.JComboBox<String> pelibox1;
    private javax.swing.JComboBox<String> salacombox;
    // End of variables declaration//GEN-END:variables
}
