/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author cris_
 */
public class Boleta extends javax.swing.JFrame {

    /**
     * Creates new form Boleta
     */
    public Boleta() {
        initComponents();
        fecha();
        obtenerDatos();
        setTitle("Cine.in");
        this.setLocationRelativeTo(null);
    }
    String dia,mes,anio,hora,min,seg;
    private void fecha() {
        Calendar c1 = Calendar.getInstance();
        Calendar c2 = new GregorianCalendar();
        dia = Integer.toString(c1.get(Calendar.DATE));
        mes = Integer.toString(c2.get(Calendar.MONTH)+1);
        anio = Integer.toString(c1.get(Calendar.YEAR));
        hora = Integer.toString(c1.get(Calendar.HOUR_OF_DAY));
        min = Integer.toString(c1.get(Calendar.MINUTE));
        seg = Integer.toString(c1.get(Calendar.SECOND));
        fecha.setText("Fecha" + dia +"/"+mes+"/"+anio);
        horas.setText("Horas:"+hora+":"+min+":"+seg);
                }
    
    private void obtenerDatos(){
    ppelicula.setText(Seleccion_Asiento.a.getText());
    sucursal.setText(Seleccion_Asiento.d.getText());
    psala.setText(Seleccion_Asiento.s.getText());
    ca.setText("Cantidad Entradas: "+Seleccion_Asiento.cantA.getText());
    funcion.setText("funcion: "+Seleccion_Asiento.funcion.getText());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fecha = new javax.swing.JLabel();
        horas = new javax.swing.JLabel();
        ppelicula = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        psala = new javax.swing.JLabel();
        ca = new javax.swing.JLabel();
        totala = new javax.swing.JLabel();
        funcion = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        sucursal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fecha.setText("fecha");
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        horas.setText("hora");
        getContentPane().add(horas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        ppelicula.setText("Pelicula:");
        getContentPane().add(ppelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel1.setText("Boleta de Entrada al Cine");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));
        getContentPane().add(psala, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 60, 20));
        getContentPane().add(ca, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 200, 20));
        getContentPane().add(totala, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 190, 20));

        funcion.setText("Funcion:");
        getContentPane().add(funcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jButton1.setText("Guardar y Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 246, -1, -1));

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 246, -1, -1));

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 246, -1, -1));

        sucursal.setText("Sucursal:");
        getContentPane().add(sucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 30, 20));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 40, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    String a= ppelicula.getText();
    String r=psala.getText();
    String fech=fecha.getText();
    String h=horas.getText();
    String s=sucursal.getText();
    String can=ca.getText();
    int n1 = Integer.parseInt(ca.getText());
    totala.setText("Total: "+(n1*3500));
    String tot = totala.getText();
      JFileChooser dlg = new JFileChooser();
          int seleccion = dlg.showSaveDialog(null);
        try {
            if (seleccion == JFileChooser.APPROVE_OPTION){
            File f = dlg.getSelectedFile();
            String f1= f.toString(); 
            FileOutputStream archivo = new FileOutputStream(f1+".pdf");
            Document doc = new Document();
            PdfWriter.getInstance(doc, archivo);
            doc.open();
            doc.add(new Paragraph(fech+"        "+h));
            doc.add(new Paragraph("------------------CineIn-------------------\n"+a + "\n"+r +"\n"+fech+"\n"+s+"\n"+can+"\n"+tot));
            doc.close();}
            JOptionPane.showMessageDialog(null,"Boleta Guardada Con Exito");
        } catch (DocumentException | HeadlessException | FileNotFoundException e) {
            JOptionPane.showMessageDialog(null,"error"+e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
    dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
    System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Boleta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    private javax.swing.JLabel ca;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel funcion;
    private javax.swing.JLabel horas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel ppelicula;
    private javax.swing.JLabel psala;
    private javax.swing.JLabel sucursal;
    private javax.swing.JLabel totala;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
