/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorUsuario;
import controlador.ControladorPersona;
import controlador.ControladorCliente;
import java.awt.Menu;
import javax.swing.JOptionPane;
import vista.Menu_admin;

/**
 *
 * @author krizz
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    ControladorUsuario cu = new ControladorUsuario();
    ControladorPersona cp = new ControladorPersona();
    ControladorCliente cc = new ControladorCliente();

    public Login() {
        initComponents();
        labelRegistra.setVisible(false);
        ButtonRegistrar.setVisible(false);
        setTitle("Cine.in");
        this.setLocationRelativeTo(null);
    }

    private void limpiar() {
        TXTnom_u.setText("");
        TXTpass.setText("");
    }
    boolean modoUsuario = true;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ButtonModo = new javax.swing.JButton();
        labelPass = new javax.swing.JLabel();
        labelNom = new javax.swing.JLabel();
        TXTnom_u = new javax.swing.JTextField();
        ButtonIniciar = new javax.swing.JButton();
        ButtonRegistrar = new javax.swing.JButton();
        TXTpass = new javax.swing.JPasswordField();
        labelRegistra = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenido a cine.in");
        jLabel1.setToolTipText("");

        ButtonModo.setText("Modo Usuario");
        ButtonModo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonModoActionPerformed(evt);
            }
        });

        labelPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelPass.setForeground(new java.awt.Color(255, 255, 255));
        labelPass.setText("Contraseña");

        labelNom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelNom.setForeground(new java.awt.Color(255, 255, 255));
        labelNom.setText("Usuario");

        TXTnom_u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTnom_uActionPerformed(evt);
            }
        });

        ButtonIniciar.setText("Entrar");
        ButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIniciarActionPerformed(evt);
            }
        });

        ButtonRegistrar.setText("Registrarse");
        ButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegistrarActionPerformed(evt);
            }
        });

        TXTpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTpassActionPerformed(evt);
            }
        });

        labelRegistra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelRegistra.setForeground(new java.awt.Color(255, 255, 255));
        labelRegistra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRegistra.setText("¿No estas registrado?");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(ButtonModo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(labelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPass, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(labelRegistra, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(ButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TXTpass, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(TXTnom_u, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(ButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel4)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ButtonModo)
                .addGap(3, 3, 3)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(labelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPass, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(labelRegistra)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(ButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TXTpass, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(TXTnom_u, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(ButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel4)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTnom_uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTnom_uActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTnom_uActionPerformed

    private void ButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIniciarActionPerformed
        if (this.modoUsuario) {
            if (TXTpass.getText().equals("") && TXTnom_u.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Por favor ingrese algún dato para procesar");
            } else if (TXTnom_u.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Por favor ingrese un nombre de usuario");
            } else if (TXTpass.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Por favor ingrese una contraseña");
            } else if (!TXTpass.getText().equals("") && !TXTnom_u.getText().equals("")) {
                if (cu.verificaExistencia(TXTnom_u.getText(), TXTpass.getText())) {
                    dispose();
                    Menu_admin menuA = new Menu_admin();
                    Menu_usuario.run.setText(TXTnom_u.getText());
                    menuA.show();
                } else {
                    limpiar();
                    JOptionPane.showMessageDialog(null, "Nombre de usuario o contraseña incorrecta");
                }
            }

        } else if (!this.modoUsuario) {
            if (TXTnom_u.getText().equals("")) {
                limpiar();
                JOptionPane.showMessageDialog(null, "Por favor ingrese su RUN");
            } else if (!TXTnom_u.getText().equals("")) {
                if (cc.verificaExistencia(cp.obtenerId_persona(TXTnom_u.getText()))) {
                    dispose();
                    Menu_usuario menuC = new Menu_usuario();
                    Menu_usuario.run.setText(TXTnom_u.getText());
                    menuC.show();
                } else {
                    limpiar();
                    JOptionPane.showMessageDialog(null, "RUN ingresado incorrecto");
                }
            }
        }
    }//GEN-LAST:event_ButtonIniciarActionPerformed

    private void TXTpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTpassActionPerformed

    private void ButtonModoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonModoActionPerformed
        if (this.modoUsuario) {
            this.modoUsuario = false;
            TXTpass.setVisible(false);
            labelPass.setVisible(false);
            labelRegistra.setVisible(true);
            ButtonRegistrar.setVisible(true);
            labelNom.setText("RUN (Formato: 12345678-9)");
            ButtonModo.setText("Modo Cliente");
        } else if (!modoUsuario) {
            this.modoUsuario = true;
            TXTpass.setVisible(true);
            labelPass.setVisible(true);
            labelRegistra.setVisible(false);
            ButtonRegistrar.setVisible(false);
            labelNom.setText("Usuario");
            ButtonModo.setText("Modo Usuario");
        }
    }//GEN-LAST:event_ButtonModoActionPerformed

    private void ButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegistrarActionPerformed
        Registrar_cliente rc = new Registrar_cliente();
        rc.show();
    }//GEN-LAST:event_ButtonRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonIniciar;
    private javax.swing.JButton ButtonModo;
    private javax.swing.JButton ButtonRegistrar;
    private javax.swing.JTextField TXTnom_u;
    private javax.swing.JPasswordField TXTpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelPass;
    private javax.swing.JLabel labelRegistra;
    // End of variables declaration//GEN-END:variables
}
