/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author krizz
 */
public class Menu_admin extends javax.swing.JFrame {

    /**
     * Creates new form Menu_admin
     */
    public Menu_admin() {
        initComponents();
        setTitle("Cine.in");
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        CerrarSesion = new javax.swing.JButton();
        AdminFunc = new javax.swing.JButton();
        ButtonEliminarU = new javax.swing.JButton();
        AdminPeli = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        VerComoUsu = new javax.swing.JButton();
        ButtonRegistrarU1 = new javax.swing.JButton();
        asientos = new javax.swing.JButton();
        ButtonModificarU = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CerrarSesion.setText("Cerrar sesion");
        CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(CerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 180, 50));

        AdminFunc.setText("Administrar funciones");
        AdminFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminFuncActionPerformed(evt);
            }
        });
        getContentPane().add(AdminFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 180, 50));

        ButtonEliminarU.setText("Eliminar Usuario");
        ButtonEliminarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarUActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonEliminarU, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 160, 50));

        AdminPeli.setText("Administrar peliculas");
        AdminPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminPeliActionPerformed(evt);
            }
        });
        getContentPane().add(AdminPeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 182, 52));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Menu principal administrador");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        VerComoUsu.setText("Ver como usuario");
        VerComoUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerComoUsuActionPerformed(evt);
            }
        });
        getContentPane().add(VerComoUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 180, 50));

        ButtonRegistrarU1.setText("Registrar Usuario");
        ButtonRegistrarU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegistrarU1ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonRegistrarU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 160, 50));

        asientos.setText("Limpiar Asientos");
        asientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asientosActionPerformed(evt);
            }
        });
        getContentPane().add(asientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 180, 50));

        ButtonModificarU.setText("Modificar Usuario");
        ButtonModificarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonModificarUActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonModificarU, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 160, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu admin.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -20, 880, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionActionPerformed
        dispose();
        Login login = new Login();
        login.show();
    }//GEN-LAST:event_CerrarSesionActionPerformed

    private void AdminPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminPeliActionPerformed
        Agregar_peli agrega = new Agregar_peli();
        agrega.show();
    }//GEN-LAST:event_AdminPeliActionPerformed

    private void AdminFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminFuncActionPerformed
        Agregar_funcion funcion = new Agregar_funcion();
        funcion.show();
    }//GEN-LAST:event_AdminFuncActionPerformed

    private void VerComoUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerComoUsuActionPerformed
        Menu_usuario user = new Menu_usuario();
        user.setVisible(true);
    }//GEN-LAST:event_VerComoUsuActionPerformed

    private void asientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asientosActionPerformed
        Estado_asiento est = new Estado_asiento();
        est.setVisible(true);
    }//GEN-LAST:event_asientosActionPerformed

    private void ButtonRegistrarU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegistrarU1ActionPerformed
        Agregar_usuario au = new Agregar_usuario();
        au.setVisible(true);
    }//GEN-LAST:event_ButtonRegistrarU1ActionPerformed

    private void ButtonModificarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonModificarUActionPerformed
        Modificar_usuario mu = new Modificar_usuario();
        mu.setVisible(true);
    }//GEN-LAST:event_ButtonModificarUActionPerformed

    private void ButtonEliminarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarUActionPerformed
        Eliminar_usuario eu = new Eliminar_usuario();
        eu.setVisible(true);
    }//GEN-LAST:event_ButtonEliminarUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminFunc;
    private javax.swing.JButton AdminPeli;
    private javax.swing.JButton ButtonEliminarU;
    private javax.swing.JButton ButtonModificarU;
    private javax.swing.JButton ButtonRegistrarU1;
    private javax.swing.JButton CerrarSesion;
    private javax.swing.JButton VerComoUsu;
    private javax.swing.JButton asientos;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
