/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorPelicula;
import controlador.Lista_peliculas;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import model.Pelicula;

/**
 *
 * @author krizz
 */
public class Menu_usuario extends javax.swing.JFrame {

    /**
     * Creates new form Menu_usuario
     */
    private List<Lista_peliculas> botones = new ArrayList<Lista_peliculas>();

    public Menu_usuario() {

        initComponents();
        setTitle("Cine.in");
        this.setLocationRelativeTo(null);
        crearAsientos();
        setPreferredSize(new Dimension(400, 400));
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }
    int contadorasi = 1;
    ControladorPelicula cpe = new ControladorPelicula();
    List<Pelicula> peliculas = new ArrayList();
    List<Pelicula> peliculas2 = new ArrayList();
    int posicionColumna = 200;
    int posicionFila = 30;
    int cantFilas = 3;
    int contador = 1;

    private void crearAsientos() {
        JScrollPane scroll = new JScrollPane();
        peliculas = new ControladorPelicula().listarPeliculas();
        peliculas2 = new ControladorPelicula().listaPortada();

        try {
            for (Pelicula temp : peliculas2) {
                Lista_peliculas nuevaPortada;
                nuevaPortada = new Lista_peliculas(temp) {
                    @Override
                    public void actionPerformed(ActionEvent ae) {
                        Entradas ent = new Entradas();
                        ent.setVisible(true);
                        Entradas.jnombre.setText("Pelicula: " + temp.getNombre());
                        ImageIcon image2 = new ImageIcon(new ImageIcon(temp.getPortada()).getImage().getScaledInstance(ent.foto.getWidth(),ent.foto.getHeight(), Image.SCALE_SMOOTH));
                        Entradas.foto.setIcon(image2);
                        Entradas.jclasificacion.setText("Clasificacion: " + temp.getClasificacion());
                        Entradas.jdirector.setText("Director :" + temp.getDirector());
                        Entradas.jreparto.setText("Reparto: " + temp.getReparto());
                        Entradas.descripcion.setText("<html>" + temp.getDescripcion() + "<html>");
                        Entradas.sala.setText("Sala: S"+temp.getSala());
                        Entradas.funcionn.setText(temp.getFuncion());
                    }
                };
                nuevaPortada.setSize(180, 230);
                nuevaPortada.setLocation(posicionFila, posicionColumna);
                posicionFila = posicionFila + 250;
                contadorasi++;
                if (contador % cantFilas == 0) {
                    posicionColumna = posicionColumna + 250;
                    posicionFila = 30;
                }
                jLabel3.add(nuevaPortada);
                this.botones.add(nuevaPortada);
                nuevaPortada.isSelected();
                contador++;

            }
        } catch (IOException ex) {
            Logger.getLogger(Menu_usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        run = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Menu principal");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PRINCIPALES EXITOS:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 126, -1, -1));

        jButton1.setText("Cerrar Sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, 114, 44));

        run.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        run.setForeground(new java.awt.Color(255, 255, 255));
        run.setText("Admi");
        getContentPane().add(run, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 159, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Bienvenido usuario:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 50, -1, -1));

        jButton2.setText("Volver a menu admin");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 640, 201, 58));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo user.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        Login log = new Login();
        log.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        Menu_admin admin = new Menu_admin();
        admin.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel run;
    // End of variables declaration//GEN-END:variables
}
